version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    image: thermal-registry-api
    volumes:
      - ./api:/app                    
      - ./api/database:/app/database
      - ./api/uploads:/app/uploads      

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app        
    depends_on:
      - api             
    environment:    
      - WATCHPACK_POLLING=true   
      - CHOKIDAR_USEPOLLING=true
    image: thermal-registry-client